services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - LOG_CHANNEL=stack
        depends_on:
            - redis
        networks:
            - laravel

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
